swagger:  "2.0"
info:
  title: Login API documentation
  version: 1.0.0
  description: This is a API to be used to login, register and create users
  contact:
    email: Rajaramsharma422@gmail.com
  license:
    name: Apache License, Version 2.0
    url: http://www.apache.org/licenses/
  servers:
    -url: https://localhost:3000
    description: this is localhost server
schemes: [http, https]
paths:
  /:
    get:
      summary: "returns string"
      description: it is used to retrieve
      responses:
          200:
            description: successful

  /login:
    post:
      summary: Login method
      responses:
        200:
          description: login successful
